

title: safal lama
email: whysafalisop@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  cyber security
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yoyuehappy
github_username:  ryuzinoh

# Build settings
theme: minima
plugins:
  - jekyll-feed

